steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'clean', 'verify', '-DskipTests' ]
    dir: ''
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'functions', 'deploy', 'eco-crafting-data',
            '--trigger-http', '--allow-unauthenticated',
            '--region', 'us-east1',
            '--runtime', 'java11',
            '--source', '.',
            '--entry-point', 'com.apex.DataRequestHandler' ]
    dir: ''
